name: Code Style

on:
  pull_request:
    paths:
      - '**.php'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Run Pint
        uses: vendor/bin/pint --test
